on: 
  push:
    branches: 
      - 'feature/**'
      - 'main'
      - 'hotfix/**'
permissions:
  id-token: write   # Required for OIDC
  contents: read    # Required for actions/checkout      

jobs:
  MyfirstJob: 
    name: My job
    runs-on: [surendra-runner,self-hosted]
    steps:
    - name: Hello Reliance faimly!
      run: echo surendra Maharaj
    - name: Azure Login
      uses: Azure/login@v2.3.0
      with:
        # ClientId of the Azure Service principal created.
        client-id: 82b37c9f-3762-4c6f-bd5f-40f0f9b40500
        # TenantId of the Azure Service principal created.
        tenant-id: e0eb0b0e-a455-477c-b0e8-56b7f7f4efb4
        # Azure subscriptionId
        subscription-id: 177b7e12-5f03-4f63-bcd1-ed6d1d776bff

    - name: Install Terraform
     
      uses: little-core-labs/install-terraform@v2.0.0
      with:
        # Version of terraform to download
        version: 1.13.0

    - name: Terraform fmt
      id: fmt
      working-directory: Git_Rivision
      run: terraform fmt -check
      continue-on-error: true

    - name: Terraform Init
      id: init
      working-directory: Git_Rivision
      run: terraform init -input=false

    - name: Terraform Validate
      id: validate
      working-directory: Git_Rivision
      run: terraform validate -no-color

    - name: Terraform Plan
      id: plan
      working-directory: Git_Rivision
      run: terraform plan -no-color -input=false
      continue-on-error: true
              
    
    
          
      
    
    
