name: my first workflow

on:
  push:
    branches:
      - 'features/**'
      - 'main'

jobs:
  terraformjob:
    runs-on: surendra-runner
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0

