name: Terraform CI/CD for Azure

on:
  push:
    branches:
      - main
      - feature/*

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ Checkout repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2️⃣ Setup Terraform (latest stable version)
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: latest


   
